// Sidebar
export const SIDEBAR_ACTIVE_MENU = "SIDEBAR_ACTIVE_MENU";
export const SIDEBAR_UPDATE_MENU = "SIDEBAR_UPDATE_MENU";
// Loader
export const LOADER_START = "LOADING_SPINNER_START";
export const LOADER_COMPLETE = "LOADING_SPINNER_COMPLETE";
export const LOADER_ERROR = "LOADING_SPINNER_ERROR";
export const FORM_LOADING_START = "FORM_LOADING_START";
export const FORM_LOADING_FINISH = "FORM_LOADING_FINISH";

// Exceptions
export const GET_ERRORS = "GET_ERRORS";